apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-build-
spec:
  serviceAccountName: ci-service-account
  entrypoint: kaniko-build
  ttlStrategy:
    secondsAfterCompletion: 10800  # 3 hours = 3 * 60 * 60 seconds
  arguments:
    parameters:
      - name: dockerfileContent
      - name: enableCuda
        value: "true"
      - name: imageName
        value: "registry.ra.se:5002/airiksarkivet/devenv:v13.5.0-test"
      - name: registry
        value: "registry.ra.se:5002" 
  templates:
    - name: kaniko-build
      dag:
        tasks:
          - name: build-image
            template: kaniko
            arguments:
              artifacts:
                - name: dockerfile 
                  raw:
                    data: "{{workflow.parameters.dockerfileContent}}"
    - name: kaniko
      inputs:
        artifacts:
          - name: dockerfile 
            path: /workspace/Dockerfile 
      container:
        image: "{{workflow.parameters.registry}}/gcr.io/kaniko-project/executor:latest" 
        command: ["/kaniko/executor"]
        args:
          - --context=dir:///workspace
          - --dockerfile=/workspace/Dockerfile
          - --destination={{workflow.parameters.imageName}}
          - --insecure
          - --insecure-registry={{workflow.parameters.registry}}
          - --build-arg=ENABLE_CUDA={{workflow.parameters.enableCuda}}
          - --build-arg=REGISTRY={{workflow.parameters.registry}}
        volumeMounts:
          - name: workspace
            mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir: {}